import jsPDF from 'jspdf';
import type { Lead, Quotation, OrderConfirmation } from '../types';
import dayjs from 'dayjs';

export const pdfService = {
  async generateQuotationPDF(q: Quotation, lead: Lead, creatorName: string): Promise<Blob> {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    // Color palette
    const emerald = [16, 185, 129];
    const slateDark = [30, 41, 59];

    // Title / Header Banner
    doc.setFillColor(emerald[0], emerald[1], emerald[2]);
    doc.rect(0, 0, 210, 32, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('ARROW SOLAR CORP', 15, 18);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Clean Energy Solutions & Standardized Installations', 15, 25);

    // Invoice Meta (Right side)
    doc.setTextColor(slateDark[0], slateDark[1], slateDark[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('QUOTATION / PROPOSAL', 130, 48);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Quote No: ${q.quotationNumber}`, 130, 55);
    doc.text(`Date: ${dayjs(q.createdAt || new Date()).format('DD MMMM YYYY')}`, 130, 60);
    doc.text(`Valid Until: ${dayjs(q.followUpDate).format('DD MMMM YYYY')}`, 130, 65);

    // Client Info
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Client Details:', 15, 48);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Name: ${lead.name}`, 15, 55);
    doc.text(`Phone: +91 ${lead.phoneNumber}`, 15, 60);
    if (lead.email) {
      doc.text(`Email: ${lead.email}`, 15, 65);
    }
    doc.text(`Project Requirement: ${lead.requirement}`, 15, 70);

    // Divider Line
    doc.setDrawColor(226, 232, 240);
    doc.line(15, 78, 195, 78);

    // Table Headers
    doc.setFillColor(248, 250, 252);
    doc.rect(15, 83, 180, 8, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('S.No', 17, 88);
    doc.text('Item Description', 35, 88);
    doc.text('Qty', 125, 88, { align: 'right' });
    doc.text('Rate (INR)', 155, 88, { align: 'right' });
    doc.text('Amount (INR)', 190, 88, { align: 'right' });

    // Table Rows
    let yPos = 97;
    doc.setFont('helvetica', 'normal');
    q.items.forEach((item, idx) => {
      doc.text(`${idx + 1}`, 17, yPos);
      
      const itemName = item.itemName.length > 42 ? item.itemName.substring(0, 39) + '...' : item.itemName;
      doc.text(itemName, 35, yPos);
      
      doc.text(`${item.qty}`, 125, yPos, { align: 'right' });
      doc.text(`Rs. ${item.rate.toLocaleString('en-IN')}`, 155, yPos, { align: 'right' });
      doc.text(`Rs. ${item.amount.toLocaleString('en-IN')}`, 190, yPos, { align: 'right' });
      
      // Row underline
      doc.setDrawColor(241, 245, 249);
      doc.line(15, yPos + 3, 195, yPos + 3);
      yPos += 10;
    });

    // Totals Box
    yPos += 2;
    doc.setFont('helvetica', 'bold');
    doc.text('Subtotal:', 140, yPos);
    doc.text(`Rs. ${q.subtotal.toLocaleString('en-IN')}`, 190, yPos, { align: 'right' });

    yPos += 6;
    doc.setFillColor(emerald[0], emerald[1], emerald[2]);
    doc.rect(130, yPos - 4, 65, 7, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text('GRAND TOTAL:', 133, yPos);
    doc.text(`Rs. ${q.grandTotal.toLocaleString('en-IN')}`, 190, yPos, { align: 'right' });

    // Terms / Sign off
    yPos += 22;
    doc.setTextColor(slateDark[0], slateDark[1], slateDark[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Terms & Conditions:', 15, yPos);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('1. Quotation validity is 30 days from the date of issue.', 15, yPos + 6);
    doc.text('2. 50% advance on order confirmation, 40% on delivery, and 10% after solar installation net metering ready.', 15, yPos + 11);
    doc.text('3. Installation will be scheduled within 7 working days of stock delivery.', 15, yPos + 16);

    // Representative details
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('Generated By:', 130, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(creatorName, 130, yPos + 5);
    doc.text('Authorized Representative', 130, yPos + 9);

    const blob = doc.output('blob');
    return blob;
  },

  async generateConfirmationPDF(
    oc: OrderConfirmation,
    lead: Lead,
    creatorName: string,
    signatureUrl: string
  ): Promise<Blob> {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const emerald = [16, 185, 129];
    const slateDark = [30, 41, 59];

    // Title / Header Banner
    doc.setFillColor(slateDark[0], slateDark[1], slateDark[2]);
    doc.rect(0, 0, 210, 32, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('ARROW SOLAR CORP', 15, 18);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Order Booking Confirmation & Receipt', 15, 25);

    // Order Meta (Right side)
    doc.setTextColor(slateDark[0], slateDark[1], slateDark[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('ORDER CONFIRMATION', 130, 48);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Booking Date: ${dayjs(oc.createdAt || new Date()).format('DD MMMM YYYY')}`, 130, 55);
    doc.text(`Payment Mode: ${oc.paymentMode.toUpperCase()}`, 130, 60);
    if (oc.paymentReference) {
      doc.text(`Ref: ${oc.paymentReference}`, 130, 65);
    }

    // Client Info
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Client Details:', 15, 48);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Name: ${lead.name}`, 15, 55);
    doc.text(`Phone: +91 ${lead.phoneNumber}`, 15, 60);
    if (lead.email) {
      doc.text(`Email: ${lead.email}`, 15, 65);
    }
    doc.text(`Project Requirement: ${lead.requirement}`, 15, 70);

    // Divider Line
    doc.setDrawColor(226, 232, 240);
    doc.line(15, 78, 195, 78);

    // Table Headers
    doc.setFillColor(248, 250, 252);
    doc.rect(15, 83, 180, 8, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('S.No', 17, 88);
    doc.text('Item Description', 35, 88);
    doc.text('Qty', 125, 88, { align: 'right' });
    doc.text('Rate (INR)', 155, 88, { align: 'right' });
    doc.text('Amount (INR)', 190, 88, { align: 'right' });

    // Table Rows
    let yPos = 97;
    doc.setFont('helvetica', 'normal');
    oc.itemsConfirmed.forEach((item, idx) => {
      doc.text(`${idx + 1}`, 17, yPos);
      const itemName = item.itemName.length > 42 ? item.itemName.substring(0, 39) + '...' : item.itemName;
      doc.text(itemName, 35, yPos);
      doc.text(`${item.qty}`, 125, yPos, { align: 'right' });
      doc.text(`Rs. ${item.rate.toLocaleString('en-IN')}`, 155, yPos, { align: 'right' });
      doc.text(`Rs. ${item.amount.toLocaleString('en-IN')}`, 190, yPos, { align: 'right' });
      
      doc.setDrawColor(241, 245, 249);
      doc.line(15, yPos + 3, 195, yPos + 3);
      yPos += 10;
    });

    // Totals Box
    yPos += 2;
    doc.setFont('helvetica', 'bold');
    doc.text('Subtotal Value:', 140, yPos);
    doc.text(`Rs. ${oc.subtotal.toLocaleString('en-IN')}`, 190, yPos, { align: 'right' });

    yPos += 6;
    doc.text('Advance Paid:', 140, yPos);
    doc.text(`Rs. ${oc.advanceAmount.toLocaleString('en-IN')}`, 190, yPos, { align: 'right' });

    yPos += 6;
    doc.setFillColor(emerald[0], emerald[1], emerald[2]);
    doc.rect(130, yPos - 4, 65, 7, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text('BALANCE DUE:', 133, yPos);
    doc.text(`Rs. ${(oc.subtotal - oc.advanceAmount).toLocaleString('en-IN')}`, 190, yPos, { align: 'right' });

    // Client Signature
    yPos += 22;
    doc.setTextColor(slateDark[0], slateDark[1], slateDark[2]);
    doc.setFont('helvetica', 'bold');
    doc.text('Client Signature & Agreement:', 15, yPos);
    
    try {
      if (signatureUrl && signatureUrl.startsWith('data:image')) {
        doc.addImage(signatureUrl, 'PNG', 15, yPos + 3, 50, 18);
      } else {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8);
        doc.text('(Signature Recorded Digitally)', 15, yPos + 8);
      }
    } catch (e) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.text('(Signature Captured & Stored)', 15, yPos + 8);
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('Authorized Signatory:', 130, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(creatorName, 130, yPos + 5);
    doc.text('Arrow Solar Representative', 130, yPos + 9);

    const blob = doc.output('blob');
    return blob;
  },

  async generateChallanPDF(ch: any): Promise<Blob> {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const primaryColor = [79, 70, 229];
    const slateDark = [30, 41, 59];

    // Header Banner
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, 210, 32, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('ARROW SOLAR CORP', 15, 18);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Materials Delivery Challan & Dispatch Note', 15, 25);

    // Meta Details
    doc.setTextColor(slateDark[0], slateDark[1], slateDark[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('DELIVERY CHALLAN', 130, 48);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Challan No: ${ch.challanNumber}`, 130, 55);
    doc.text(`Date: ${dayjs(ch.createdAt || new Date()).format('DD MMMM YYYY')}`, 130, 60);
    doc.text(`Vehicle No: ${ch.vehicleNumber}`, 130, 65);

    // Client Info
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Deliver To (Customer):', 15, 48);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Client Name: ${ch.leadName}`, 15, 55);
    doc.text(`Project Ref ID: ${ch.leadId}`, 15, 60);

    // Transport Info
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Transport Details:', 15, 70);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Driver Name: ${ch.driverName}`, 15, 77);
    doc.text(`Driver Phone: +91 ${ch.driverPhone}`, 15, 82);
    doc.text(`Assigned Representative: ${ch.employeeName}`, 15, 87);

    // Divider Line
    doc.setDrawColor(226, 232, 240);
    doc.line(15, 93, 195, 93);

    // Table Headers
    doc.setFillColor(248, 250, 252);
    doc.rect(15, 98, 180, 8, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('S.No', 17, 103);
    doc.text('Item Description', 35, 103);
    doc.text('Dispatched Qty', 190, 103, { align: 'right' });

    // Table Rows
    let yPos = 112;
    doc.setFont('helvetica', 'normal');
    ch.items.forEach((item: any, idx: number) => {
      doc.text(`${idx + 1}`, 17, yPos);
      doc.text(item.productName, 35, yPos);
      doc.text(`${item.qty} units`, 190, yPos, { align: 'right' });
      
      doc.setDrawColor(241, 245, 249);
      doc.line(15, yPos + 3, 195, yPos + 3);
      yPos += 10;
    });

    // Terms / Signatures
    yPos += 15;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Receipt Acknowledgement:', 15, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('Received the above mentioned items in good condition.', 15, yPos + 6);

    yPos += 20;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text("Receiver's Signature", 15, yPos);
    doc.line(15, yPos - 10, 60, yPos - 10);

    doc.text('Authorized Signatory', 130, yPos);
    doc.line(130, yPos - 10, 175, yPos - 10);

    const blob = doc.output('blob');
    return blob;
  }
};
